"use client";

import Image from "next/image";
import { useState } from "react";
import { SparkIcon } from "@/components/ui/icons";
import type { ApiErrorBody } from "@/lib/assessment/contract";

// Optional AI explanation on the results page, voiced by bAI, BasaCheck's
// heron. Runs only when the teacher asks. The teacher still chooses the
// activity in the cards below.

type Recommendation = {
  activityTitle: string;
  optional: boolean;
  summary: string;
  reasons: string[];
  tips: string[];
  model: string;
};

type State =
  | { name: "idle" }
  | { name: "loading" }
  | { name: "done"; recommendation: Recommendation }
  | { name: "error"; message: string };

export function AiRecommendation({ assessmentId }: { assessmentId: string }) {
  const [state, setState] = useState<State>({ name: "idle" });

  async function generate() {
    setState({ name: "loading" });
    try {
      const response = await fetch(`/api/assessments/${assessmentId}/ai-recommendation`, { method: "POST" });
      const body: unknown = await response.json().catch(() => null);
      if (!response.ok) {
        const message = (body as Partial<ApiErrorBody> | null)?.error?.message;
        setState({ name: "error", message: message ?? "The AI recommendation is unavailable. Choose an activity yourself." });
        return;
      }
      setState({ name: "done", recommendation: body as Recommendation });
    } catch {
      setState({ name: "error", message: "Could not reach the BasaCheck server. Try again." });
    }
  }

  return (
    <section aria-labelledby="ai-heading" className="max-w-3xl space-y-3">
      <div className="flex items-center justify-between gap-2">
        <h2 id="ai-heading" className="text-lg font-semibold">
          Ask bAI
        </h2>
        <span className="tag">Optional · AI</span>
      </div>

      <div className="flex items-start gap-3">
        <Image
          src="/bai.jpg"
          alt="bAI"
          width={96}
          height={96}
          className={`mascot size-11 shrink-0 ${state.name === "loading" ? "splash-heron-idle" : ""}`}
        />
        <div className="bubble bubble-tail-left min-w-0 flex-1 space-y-3 p-4">
          {state.name === "done" ? (
            <>
              <p className="note-dashed text-xs font-medium">
                AI-generated. Check it before using it. It cannot change scores, and you choose the
                activity.
              </p>
              <div>
                <p className="font-semibold">
                  {state.recommendation.optional ? "Optional practice" : "Suggested activity"}:{" "}
                  {state.recommendation.activityTitle}
                </p>
                <p className="mt-0.5 text-xs text-muted">
                  {state.recommendation.optional
                    ? "These results do not call for a specific activity under the demo rules."
                    : "Matches the demo rule's suggestion. Demo rules are not validated educational benchmarks."}
                </p>
              </div>
              <p className="text-sm text-ink">{state.recommendation.summary}</p>
              <div>
                <h3 className="text-sm font-semibold">Why</h3>
                <ul className="mt-1 list-disc space-y-1 pl-5 text-sm text-ink-2">
                  {state.recommendation.reasons.map((reason) => (
                    <li key={reason}>{reason}</li>
                  ))}
                </ul>
              </div>
              <div>
                <h3 className="text-sm font-semibold">Classroom tips</h3>
                <ul className="mt-1 list-disc space-y-1 pl-5 text-sm text-ink-2">
                  {state.recommendation.tips.map((tip) => (
                    <li key={tip}>{tip}</li>
                  ))}
                </ul>
              </div>
              <p className="meta text-xs">
                Generated by {state.recommendation.model} from BasaCheck&apos;s measurements. No
                learner name was sent.
              </p>
            </>
          ) : state.name === "loading" ? (
            <p role="status" className="text-sm text-ink">
              Reading the results
              <span className="splash-dot">.</span>
              <span className="splash-dot" style={{ animationDelay: "150ms" }}>
                .
              </span>
              <span className="splash-dot" style={{ animationDelay: "300ms" }}>
                .
              </span>
            </p>
          ) : (
            <p className="text-sm text-ink">Need help reading these results? Ask me.</p>
          )}

          {state.name === "error" && (
            <p role="alert" className="alert">
              {state.message}
            </p>
          )}
        </div>
      </div>

      <button
        type="button"
        onClick={generate}
        disabled={state.name === "loading"}
        className="btn btn-secondary w-full sm:w-auto sm:min-w-56"
      >
        <SparkIcon size={16} className="text-teal" />
        {state.name === "loading" ? "bAI is thinking…" : state.name === "done" ? "Ask again" : "Ask bAI"}
      </button>
    </section>
  );
}
