"use client";

import { useState } from "react";
import type { ApiErrorBody } from "@/lib/assessment/contract";

// Optional AI explanation on the results page. Runs only when the teacher asks.
// The teacher still chooses the activity in the cards below.

type Recommendation = {
  activityTitle: string;
  optional: boolean;
  summary: string;
  reasons: string[];
  tips: string[];
  model: string;
};

type State =
  | { name: "idle" }
  | { name: "loading" }
  | { name: "done"; recommendation: Recommendation }
  | { name: "error"; message: string };

export function AiRecommendation({ assessmentId }: { assessmentId: string }) {
  const [state, setState] = useState<State>({ name: "idle" });

  async function generate() {
    setState({ name: "loading" });
    try {
      const response = await fetch(`/api/assessments/${assessmentId}/ai-recommendation`, { method: "POST" });
      const body: unknown = await response.json().catch(() => null);
      if (!response.ok) {
        const message = (body as Partial<ApiErrorBody> | null)?.error?.message;
        setState({ name: "error", message: message ?? "The AI recommendation is unavailable. Choose an activity yourself." });
        return;
      }
      setState({ name: "done", recommendation: body as Recommendation });
    } catch {
      setState({ name: "error", message: "Could not reach the BasaCheck server. Try again." });
    }
  }

  return (
    <section aria-labelledby="ai-heading" className="space-y-3 rounded-xl border border-teal-200 bg-teal-50 p-4">
      <div className="flex items-center justify-between gap-2">
        <h2 id="ai-heading" className="text-lg font-bold text-teal-950">
          AI recommendation
        </h2>
        <span className="rounded bg-white px-2 py-0.5 text-xs font-semibold text-teal-900">Optional</span>
      </div>

      {state.name === "done" ? (
        <div className="space-y-3">
          <p className="rounded bg-amber-100 px-2 py-1 text-xs font-semibold text-amber-900">
            AI-generated. Check it before using it. It cannot change scores, and you choose the activity.
          </p>
          <div>
            <p className="font-semibold text-teal-950">
              {state.recommendation.optional ? "Optional practice" : "Suggested activity"}:{" "}
              {state.recommendation.activityTitle}
            </p>
            <p className="text-xs text-teal-900">
              {state.recommendation.optional
                ? "These results do not call for a specific activity under the demo rules."
                : "Matches the demo rule's suggestion. Demo rules are not validated educational benchmarks."}
            </p>
          </div>
          <p className="text-sm text-teal-950">{state.recommendation.summary}</p>
          <div>
            <h3 className="text-sm font-semibold text-teal-950">Why</h3>
            <ul className="list-disc space-y-1 pl-5 text-sm text-teal-950">
              {state.recommendation.reasons.map((reason) => (
                <li key={reason}>{reason}</li>
              ))}
            </ul>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-teal-950">Classroom tips</h3>
            <ul className="list-disc space-y-1 pl-5 text-sm text-teal-950">
              {state.recommendation.tips.map((tip) => (
                <li key={tip}>{tip}</li>
              ))}
            </ul>
          </div>
          <p className="text-xs text-teal-900">
            Generated by {state.recommendation.model} from BasaCheck&apos;s measurements. No learner name was
            sent.
          </p>
        </div>
      ) : (
        <p className="text-sm text-teal-950">
          Get a plain-English explanation of these results and which activity card fits. It uses only
          BasaCheck&apos;s numbers and never the learner&apos;s name.
        </p>
      )}

      {state.name === "error" && (
        <p role="alert" className="rounded-lg border border-red-300 bg-red-50 p-3 text-sm text-red-950">
          {state.message}
        </p>
      )}

      <button
        type="button"
        onClick={generate}
        disabled={state.name === "loading"}
        className="min-h-12 w-full rounded-lg bg-teal-700 px-4 font-semibold text-white hover:bg-teal-800 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-700 disabled:cursor-not-allowed disabled:bg-neutral-400"
      >
        {state.name === "loading"
          ? "Asking the AI…"
          : state.name === "done"
            ? "Ask again"
            : "Get AI recommendation"}
      </button>
    </section>
  );
}
