import "server-only";
import { round1 } from "@/lib/comparison";
import { INTERVENTION_IDS, INTERVENTIONS, isInterventionId, suggestedIntervention } from "@/lib/interventions";
import type { AssessmentRow, InterventionId } from "@/lib/types";

// Optional AI explanation of one completed check, generated by a free Groq
// model. BasaCheck's deterministic engine computes every number; the AI only
// explains them and recommends one of the three static activity cards. It never
// receives the learner's name or any IDs, and it cannot change scores.

const GROQ_URL = "https://api.groq.com/openai/v1/chat/completions";
const DEFAULT_MODEL = "openai/gpt-oss-120b";
const TIMEOUT_MS = 20_000;

// Never shown to a teacher: diagnosis or condition language, and fluency or
// speed judgments (Reading Rate is a measurement, not a fluency diagnosis).
const BLOCKED_LANGUAGE =
  /dyslexi|disorder|disabilit|adhd|autis|impairment|deficit|fluen|\bslow|\bfast|\bmoderate|\bwpm\b|words per minute|reading rate/i;

// Same wording as components/ProvenanceLabels.tsx.
const LABELS = {
  tap: "Offline tap: the teacher marked missed words; not transcribed from a recording.",
  demo: "Demo Mode: this transcript was not produced by a live recording.",
  seeded: "Seeded demo assessment.",
};

const SYSTEM_PROMPT = [
  "You help an early-grade teacher understand one BasaCheck reading check. You receive facts computed by BasaCheck's deterministic scoring code.",
  "Rules:",
  "- Use only the facts given. Quote numbers exactly as given; never calculate, estimate or change a score.",
  "- Never diagnose the learner or name a reading disorder, disability or condition.",
  "- Never mention reading speed, reading rate or fluency. They are not part of these facts and never decide an activity. Do not use the words fluency, fluent, fluently, speed, pace, slow, fast, moderate, WPM or rate.",
  "- Call wordDifferences 'differences', never 'errors' or 'mistakes'. A substitution can be a synonym; do not guess what the learner understood.",
  "- Recommend exactly one activity from activityCards, by its id. If demoRule.suggestedActivityId is set, recommend that activity. If it is null, say that no activity is required by these results and present your pick as optional practice, based only on the word differences and comprehension.",
  "- The demo rules are not validated educational benchmarks.",
  "- If labels are given, mention that the data is labeled that way.",
  "- The teacher decides. Write plain, encouraging English for the teacher, not the learner.",
  '- Write every sentence in English, even when the passage is Filipino. When you mention a Filipino word from wordDifferences, keep it in quotes and add its English meaning in parentheses, for example "upang" (in order to).',
  'Respond with JSON only: {"activityId": "main-idea" | "word-practice" | "repeated-reading", "summary": "at most 3 sentences", "reasons": ["1 to 3 short reasons"], "tips": ["1 to 3 short classroom tips based on the chosen card\'s steps and the word differences"]}',
].join("\n");

export type AiRecommendation = {
  activityId: InterventionId;
  activityTitle: string;
  // True when the demo rule makes no suggestion, so the pick is optional practice.
  optional: boolean;
  summary: string;
  reasons: string[];
  tips: string[];
  model: string;
};

export type AiErrorCode =
  | "ai_not_configured"
  | "ai_rate_limited"
  | "ai_timeout"
  | "ai_unavailable"
  | "ai_invalid_response";

const ERRORS: Record<AiErrorCode, { status: number; message: string }> = {
  ai_not_configured: {
    status: 503,
    message: "AI recommendations are not set up. Add GROQ_API_KEY to .env.local and restart BasaCheck.",
  },
  ai_rate_limited: {
    status: 429,
    message: "The free AI limit for this minute was reached. Wait about a minute and try again, or choose an activity yourself.",
  },
  ai_timeout: { status: 504, message: "The AI took too long to answer. Try again, or choose an activity yourself." },
  ai_unavailable: {
    status: 502,
    message: "The AI service is busy or unavailable. Try again in a minute, or choose an activity yourself.",
  },
  ai_invalid_response: {
    status: 502,
    message: "The AI answer did not follow BasaCheck's rules, so it is not shown. Choose an activity yourself.",
  },
};

export class AiRecommendationError extends Error {
  readonly code: AiErrorCode;
  readonly status: number;
  // Which rule rejected the answer, for server logs only (never the AI text).
  readonly reason: string | undefined;

  constructor(code: AiErrorCode, reason?: string) {
    super(ERRORS[code].message);
    this.name = "AiRecommendationError";
    this.code = code;
    this.status = ERRORS[code].status;
    this.reason = reason;
  }
}

// The only data sent to the AI: no learner name, no IDs, no transcript, and no
// Reading Rate, which must never drive a suggestion (the teacher sees it on
// the page).
export function buildRecommendationFacts(assessment: AssessmentRow, passageTitle: string) {
  const labels: string[] = [];
  if (assessment.inputMode === "tap") labels.push(LABELS.tap);
  if (assessment.demoTranscript) labels.push(LABELS.demo);
  if (assessment.seededDemo) labels.push(LABELS.seeded);
  const display = (value: number | null) => (value === null ? null : round1(value));

  return {
    passageTitle,
    passageLanguage: assessment.language === "fil" ? "Filipino" : "English",
    labels,
    measurements: {
      passageReadingAccuracyPercent: display(assessment.accuracyPercent),
      comprehensionPercent: display(assessment.comprehensionPercent),
    },
    wordDifferences: assessment.wordEvents.filter((event) => event.type !== "match"),
    demoRule: {
      supportArea: assessment.supportArea,
      suggestedActivityId: suggestedIntervention(assessment.supportArea),
      note: "Demo rules, not validated educational benchmarks.",
    },
    teacherChosenActivityId: assessment.interventionId,
    activityCards: INTERVENTION_IDS.map((id) => ({
      id,
      title: INTERVENTIONS[id].title.en,
      steps: INTERVENTIONS[id].steps.en,
    })),
  };
}

export type RecommendationFacts = ReturnType<typeof buildRecommendationFacts>;

function stringList(value: unknown, max: number): string[] | null {
  if (!Array.isArray(value) || value.length === 0) return null;
  const items = value.filter((item): item is string => typeof item === "string" && item.trim().length > 0);
  if (items.length !== value.length) return null;
  return items.slice(0, max).map((item) => item.trim().slice(0, 300));
}

// Validates the model's JSON; anything off-contract is rejected, not repaired.
// When the demo rule suggests an activity, the AI must recommend that one.
export function parseRecommendation(
  content: string,
  model: string,
  demoSuggestion: InterventionId | null = null,
): AiRecommendation {
  const json = content.trim().replace(/^```(?:json)?\s*|\s*```$/g, "");
  let data: Record<string, unknown>;
  try {
    data = JSON.parse(json) as Record<string, unknown>;
  } catch {
    throw new AiRecommendationError("ai_invalid_response", "not JSON");
  }

  const reasons = stringList(data.reasons, 3);
  const tips = stringList(data.tips, 3);
  const summary = typeof data.summary === "string" ? data.summary.trim().slice(0, 800) : "";
  if (!isInterventionId(data.activityId) || !summary || !reasons || !tips) {
    throw new AiRecommendationError("ai_invalid_response", "missing or invalid fields");
  }
  const blocked = [summary, ...reasons, ...tips].join(" ").match(BLOCKED_LANGUAGE);
  if (blocked) {
    throw new AiRecommendationError("ai_invalid_response", `blocked wording "${blocked[0]}"`);
  }
  if (demoSuggestion && data.activityId !== demoSuggestion) {
    throw new AiRecommendationError("ai_invalid_response", `chose ${data.activityId}, demo rule says ${demoSuggestion}`);
  }

  return {
    activityId: data.activityId,
    activityTitle: INTERVENTIONS[data.activityId].title.en,
    optional: demoSuggestion === null,
    summary,
    reasons,
    tips,
    model,
  };
}

// One automatic retry when an answer breaks a rule; the rejected answer is
// never shown. Service errors and timeouts are not retried.
export async function requestRecommendation(
  facts: RecommendationFacts,
  fetchImpl: typeof fetch = fetch,
): Promise<AiRecommendation> {
  try {
    return await requestOnce(facts, fetchImpl);
  } catch (error) {
    if (error instanceof AiRecommendationError && error.code === "ai_invalid_response") {
      return requestOnce(facts, fetchImpl);
    }
    throw error;
  }
}

async function requestOnce(facts: RecommendationFacts, fetchImpl: typeof fetch): Promise<AiRecommendation> {
  const apiKey = process.env.GROQ_API_KEY?.trim();
  if (!apiKey) throw new AiRecommendationError("ai_not_configured");
  const model = process.env.GROQ_MODEL?.trim() || DEFAULT_MODEL;

  let response: Response;
  try {
    response = await fetchImpl(GROQ_URL, {
      method: "POST",
      headers: { authorization: `Bearer ${apiKey}`, "content-type": "application/json" },
      body: JSON.stringify({
        model,
        temperature: 0.2,
        max_completion_tokens: 800,
        // gpt-oss models think before answering; "low" keeps each request well
        // inside the free tier's tokens-per-minute limit.
        ...(model.startsWith("openai/gpt-oss") ? { reasoning_effort: "low" } : {}),
        response_format: { type: "json_object" },
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content: JSON.stringify(facts) },
        ],
      }),
      cache: "no-store",
      signal: AbortSignal.timeout(TIMEOUT_MS),
    });
  } catch (error) {
    if (error instanceof Error && error.name === "TimeoutError") throw new AiRecommendationError("ai_timeout");
    throw new AiRecommendationError("ai_unavailable");
  }

  if (response.status === 429) throw new AiRecommendationError("ai_rate_limited");
  if (!response.ok) throw new AiRecommendationError("ai_unavailable");
  const body = (await response.json().catch(() => null)) as {
    choices?: { message?: { content?: unknown } }[];
  } | null;
  const content = body?.choices?.[0]?.message?.content;
  if (typeof content !== "string") throw new AiRecommendationError("ai_invalid_response");
  return parseRecommendation(content, model, facts.demoRule.suggestedActivityId);
}
